xwr16xx/mmw/mss/mmw_cli.c File Reference
mmw_cli.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <xdc/runtime/System.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/drivers/uart/UART.h>
#include <ti/control/mmwavelink/mmwavelink.h>
#include <ti/utils/cli/cli.h>
#include <ti/utils/mathutils/mathutils.h>
#include <ti/demo/xwr16xx/mmw/include/mmw_config.h>
#include <ti/demo/xwr16xx/mmw/mss/mmw_mss.h>
#include <ti/demo/utils/mmwdemo_adcconfig.h>
#include <ti/demo/utils/mmwdemo_rfparser.h>
Macros
#define MMWDEMO_DATAUART_MAX_BAUDRATE_SUPPORTED 3125000
Functions
static int32_t MmwDemo_CLICfarCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIMultiObjBeamForming (int32_t argc, char *argv[])
static int32_t MmwDemo_CLICalibDcRangeSig (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIClutterRemoval (int32_t argc, char *argv[])
static int32_t MmwDemo_CLISensorStart (int32_t argc, char *argv[])
static int32_t MmwDemo_CLISensorStop (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIGuiMonSel (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIADCBufCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLICfarFovCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIAoAFovCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIExtendedMaxVelocity (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIBpmCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIChirpQualityRxSatMonCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIChirpQualitySigImgMonCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIAnalogMonitorCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLILvdsStreamCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIConfigDataPort (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIGetSubframe (int32_t argc, char *argv[], int32_t expectedArgc, int8_t *subFrameNum)
static int32_t MmwDemo_CLIQueryDemoStatus (int32_t argc, char *argv[])
static int32_t MmwDemo_CLICalibDataSaveRestore (int32_t argc, char *argv[])
void MmwDemo_CLIInit (uint8_t taskPriority)
Variables
MmwDemo_MSS_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Macro Definition Documentation
#define MMWDEMO_DATAUART_MAX_BAUDRATE_SUPPORTED 3125000
Definition at line 103 of file mmw_cli.c.
Referenced by MmwDemo_CLIConfigDataPort().
Function Documentation
static int32_t MmwDemo_CLIADCBufCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for data logger set command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 795 of file mmw_cli.c.
References MmwDemo_ADCBufCfg_t::adcFmt, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_ADCBufCfg_t::chirpThreshold, CLI_write(), MmwDemo_ADCBufCfg_t::iqSwapSel, MMWDEMO_ADCBUFCFG_OFFSET, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), MmwDemo_SensorState_STARTED, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIAnalogMonitorCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for enabling analog monitors
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1110 of file mmw_cli.c.
References MmwDemo_MSS_MCB_t::anaMonCfg, CLI_write(), MmwDemo_MSS_MCB_t::isAnaMonCfgPending, MmwDemo_SensorState_STARTED, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIAoAFovCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for AoA FOV (Field Of View) configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 575 of file mmw_cli.c.
References DPU_AoAProc_FovAoaCfg_t::maxAzimuthDeg, DPU_AoAProc_FovAoaCfg_t::maxElevationDeg, DPU_AoAProc_FovAoaCfg_t::minAzimuthDeg, DPU_AoAProc_FovAoaCfg_t::minElevationDeg, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), and MMWDEMO_FOVAOA_OFFSET.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIBpmCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for BPM configuration supported by the mmw Demo Note that there is a generic BPM configuration command supported by utils/cli and mmwave. The generic BPM command is not supported by the demo as the mmw demo assumes a specific BPM pattern for the TX antennas.
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 946 of file mmw_cli.c.
References MmwDemo_BpmCfg_t::chirp0Idx, MmwDemo_BpmCfg_t::chirp1Idx, CLI_write(), MmwDemo_BpmCfg_t::isEnabled, MMWDEMO_BPMCFG_OFFSET, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), MmwDemo_SensorState_STARTED, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLICalibDataSaveRestore (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for save/restore calibration data to/from flash
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1320 of file mmw_cli.c.
References MmwDemo_MSS_MCB_t::calibCfg, CLI_write(), MmwDemo_calibCfg_t::flashOffset, MmwDemo_MSS_MCB_t::isCalibCfgPending, MmwDemo_SensorState_STARTED, MmwDemo_calibCfg_t::restoreEnable, MmwDemo_calibCfg_t::saveEnable, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLICalibDcRangeSig (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for DC range calibration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 691 of file mmw_cli.c.
References CLI_write(), DPU_RANGEPROC_SIGNATURE_COMP_MAX_BIN_SIZE, DPU_RangeProc_CalibDcRangeSigCfg_t::enabled, MMWDEMO_CALIBDCRANGESIG_OFFSET, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), DPU_RangeProc_CalibDcRangeSigCfg_t::negativeBinIdx, DPU_RangeProc_CalibDcRangeSigCfg_t::numAvgChirps, and DPU_RangeProc_CalibDcRangeSigCfg_t::positiveBinIdx.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLICfarCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for CFAR configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 455 of file mmw_cli.c.
References DPU_CFARCAProc_CfarCfg_t::averageMode, CLI_write(), DPU_CFARCAProc_CfarCfg_t::cyclicMode, DPU_CFARCAProc_CfarCfg_t::guardLen, MMWDEMO_CFAR_THRESHOLD_ENCODING_FACTOR, MMWDEMO_CFARCFGDOPPLER_OFFSET, MMWDEMO_CFARCFGRANGE_OFFSET, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), DPU_CFARCAProc_CfarCfg_t::noiseDivShift, DPU_CFARCAProc_CfarCfg_t::peakGroupingEn, DPU_CFARCAProc_CfarCfg_t::thresholdScale, and DPU_CFARCAProc_CfarCfg_t::winLen.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLICfarFovCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for CFAR FOV (Field Of View) configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 527 of file mmw_cli.c.
References DPU_CFARCAProc_FovCfg_t::max, DPU_CFARCAProc_FovCfg_t::min, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), MMWDEMO_FOVDOPPLER_OFFSET, and MMWDEMO_FOVRANGE_OFFSET.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIChirpQualityRxSatMonCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for configuring CQ RX Saturation monitor
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 999 of file mmw_cli.c.
References CLI_write(), MmwDemo_MSS_MCB_t::cqSatMonCfg, MmwDemo_SensorState_STARTED, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIChirpQualitySigImgMonCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for configuring CQ Signal & Image band monitor
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1056 of file mmw_cli.c.
References CLI_write(), MmwDemo_MSS_MCB_t::cqSigImgMonCfg, MmwDemo_SensorState_STARTED, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIClutterRemoval (int32_t argc, char * argv[]) static
Description
Clutter removal Configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 757 of file mmw_cli.c.
References DPC_ObjectDetection_StaticClutterRemovalCfg_Base_t::enabled, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), and MMWDEMO_STATICCLUTTERREMOFVAL_OFFSET.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for compensation of range bias and channel phase offsets
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 843 of file mmw_cli.c.
References CLI_write(), DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, cmplx16ImRe_t_::imag, MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, cmplx16ImRe_t_::real, DPU_AoAProc_compRxChannelBiasCfg_t::rxChPhaseComp, SYS_COMMON_NUM_RX_CHANNEL, and SYS_COMMON_NUM_TX_ANTENNAS.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIConfigDataPort (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for configuring the data port
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1212 of file mmw_cli.c.
References MmwDemo_MSS_MCB_t::cfg, CLI_write(), MmwDemo_platformCfg_t::loggingBaudRate, MmwDemo_MSS_MCB_t::loggingUartHandle, MMWDEMO_DATAUART_MAX_BAUDRATE_SUPPORTED, MmwDemo_SensorState_STARTED, MmwDemo_Cfg_t::platformCfg, MmwDemo_MSS_MCB_t::sensorState, and MmwDemo_platformCfg_t::sysClockFrequency.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIExtendedMaxVelocity (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for extended maximum velocity configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 615 of file mmw_cli.c.
References DPU_AoAProc_ExtendedMaxVelocityCfg_t::enabled, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), and MMWDEMO_EXTMAXVEL_OFFSET.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIGetSubframe (int32_t argc, char * argv[], int32_t expectedArgc, int8_t * subFrameNum) static
Description
Utility function to get sub-frame number
Parameters
[in] argc Number of arguments
[in] argv Arguments
[in] expectedArgc Expected number of arguments
[out] subFrameNum Sub-frame Number (0 based)
Return values
Success - 0
Error - <0
Definition at line 370 of file mmw_cli.c.
References CLI_write().
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), and MmwDemo_CLIMultiObjBeamForming().
static int32_t MmwDemo_CLIGuiMonSel (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for gui monitoring configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 413 of file mmw_cli.c.
References MmwDemo_GuiMonSel_t::detectedObjects, MmwDemo_GuiMonSel_t::logMagRange, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), MMWDEMO_GUIMONSEL_OFFSET, MmwDemo_GuiMonSel_t::noiseProfile, MmwDemo_GuiMonSel_t::rangeAzimuthHeatMap, MmwDemo_GuiMonSel_t::rangeDopplerHeatMap, and MmwDemo_GuiMonSel_t::statsInfo.
Referenced by MmwDemo_CLIInit().
void MmwDemo_CLIInit (uint8_t taskPriority)
Description
This is the CLI Execution Task
Return values
Not Applicable.
Definition at line 1353 of file mmw_cli.c.
References CLI_open(), CLI_Cfg_t::cliBanner, CLI_Cfg_t::cliPrompt, CLI_Cfg_t::cliUartHandle, CLI_CmdTableEntry_t::cmd, CLI_CmdTableEntry_t::cmdHandlerFxn, MmwDemo_MSS_MCB_t::commandUartHandle, MmwDemo_MSS_MCB_t::ctrlHandle, CLI_Cfg_t::enableMMWaveExtension, CLI_CmdTableEntry_t::helpString, CLI_Cfg_t::mmWaveHandle, MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDataSaveRestore(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIConfigDataPort(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLIQueryDemoStatus(), MmwDemo_CLISensorStart(), MmwDemo_CLISensorStop(), CLI_Cfg_t::overridePlatform, CLI_Cfg_t::overridePlatformString, CLI_Cfg_t::socHandle, MmwDemo_MSS_MCB_t::socHandle, CLI_Cfg_t::tableEntry, CLI_Cfg_t::taskPriority, and CLI_Cfg_t::usePolledMode.
Referenced by MmwDemo_initTask().
static int32_t MmwDemo_CLILvdsStreamCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the High Speed Interface
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1150 of file mmw_cli.c.
References CLI_write(), MmwDemo_LvdsStreamCfg_t::dataFmt, MmwDemo_LvdsStreamCfg_t::isHeaderEnabled, MmwDemo_LvdsStreamCfg_t::isSwEnabled, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_DISABLED, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), MMWDEMO_LVDSSTREAMCFG_OFFSET, MmwDemo_SensorState_STARTED, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for measurement configuration of range bias and channel phase offsets
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 900 of file mmw_cli.c.
References CLI_write(), DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::enabled, MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::searchWinSize, and DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::targetDistance.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIMultiObjBeamForming (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for multi object beam forming configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 652 of file mmw_cli.c.
References DPU_AoAProc_MultiObjBeamFormingCfg_t::enabled, MmwDemo_CfgUpdate(), MmwDemo_CLIGetSubframe(), MMWDEMO_MULTIOBJBEAMFORMING_OFFSET, and DPU_AoAProc_MultiObjBeamFormingCfg_t::multiPeakThrsScal.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIQueryDemoStatus (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for querying Demo status
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1297 of file mmw_cli.c.
References MmwDemo_MSS_MCB_t::cfg, CLI_write(), MmwDemo_platformCfg_t::loggingBaudRate, MmwDemo_Cfg_t::platformCfg, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLISensorStart (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the sensor start command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 123 of file mmw_cli.c.
References MMWave_OpenCfg_t::adcOutCfg, MmwDemo_MSS_MCB_t::cfg, MMWave_OpenCfg_t::chCfg, CLI_getMMWaveExtensionConfig(), CLI_getMMWaveExtensionOpenConfig(), CLI_write(), MmwDemo_Cfg_t::ctrlCfg, MMWave_OpenCfg_t::lowPowerMode, MmwDemo_configSensor(), MmwDemo_debugAssert, MmwDemo_isAllCfgInNonPendingState(), MmwDemo_isAllCfgInPendingState(), MmwDemo_openSensor(), MmwDemo_RFParser_getNumSubFrames(), MmwDemo_SensorState_INIT, MmwDemo_SensorState_OPENED, MmwDemo_SensorState_STARTED, MmwDemo_startSensor(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_Cfg_t::openCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLISensorStop (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the sensor stop command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 337 of file mmw_cli.c.
References CLI_write(), MmwDemo_resetStaticCfgPendingState(), MmwDemo_SensorState_INIT, MmwDemo_SensorState_OPENED, MmwDemo_SensorState_STOPPED, MmwDemo_stopSensor(), and MmwDemo_MSS_MCB_t::sensorState.
Referenced by MmwDemo_CLIInit().
Variable Documentation
MmwDemo_MSS_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 666 of file mss_main.c.
Copyright 2020, Texas Instruments Incorporated